In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [5]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# get scalar back as python int
scalar.item()

7

In [8]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
# matrix
matrix = torch.tensor([
    [7,8],
    [9,10],
])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [16]:
matrix.shape

torch.Size([2, 2])

In [17]:
# tensor
tensor = torch.tensor([[
    [1,2,3],
    [3,6,9],
    [2,4,5]
    ]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
tensor.ndim

3

In [19]:
tensor.shape

torch.Size([1, 3, 3])

In [25]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [23]:
tensor2 = torch.tensor([[
    [1,2,3],
    [3,6,9],
    [2,4,5]
    ],[
    [1,2,3],
    [3,6,9],
    [2,4,5]
    ]])
tensor2

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [26]:
tensor2.ndim

3

In [27]:
tensor2.shape

torch.Size([2, 3, 3])

In [29]:
tensor2[1]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

random tensors?

why random tensors?

random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

start with random numbers ----> look at data ----> update random numbers ----> look at data ----> update random numbers

In [33]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2132, 0.4736, 0.6964, 0.6939],
        [0.3085, 0.8416, 0.2754, 0.7048],
        [0.1305, 0.8940, 0.0206, 0.5758]])

In [31]:
random_tensor.ndim

2

In [34]:
# create a random tensor with a similiar shape to an image tensor
random_image_size_tensor = torch.rand(224, 224, 3) # height width color_channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [35]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4)) # using size is the same as not using it because its the default
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [46]:
# use torch.range()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros 

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors ot on the right device

In [54]:
# float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None, # what data type the tensor is (e.g. float32, int32, float16, etc)
    device=None, # which device the tensor is stored and run on aka cpu or gpu or tpu
    requires_grad=False # whether or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [55]:
float_32_tensor.dtype

torch.float32

In [58]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [59]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [61]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [62]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - tensor.dtype
2. Tensors not right shape - tensor.shape
3. Tensors ot on the right device - tensor.device

In [63]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7042, 0.6623, 0.5200, 0.6134],
        [0.8788, 0.1445, 0.2958, 0.0348],
        [0.6256, 0.1124, 0.9253, 0.9417]])

In [70]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7042, 0.6623, 0.5200, 0.6134],
        [0.8788, 0.1445, 0.2958, 0.0348],
        [0.6256, 0.1124, 0.9253, 0.9417]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [78]:
# Create a tensor and add ten to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [79]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [80]:
# Subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [81]:
# try out the pytorch built in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [82]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

imagine these matrices: 
Matrix A has 1 row and 3 columns
Matrix B has 3 rows and 2 columns

1. Matrix A must have the same columns as rows in matrix B
We can multiply A by B because 3 columns in A = 3 rows in B
But we cannot multiply B by A because 2 columns in B does not = 1 row in A

When we do multiply A by B the resulting matrix will have the same number of rows as matrix A and the same number of columns as matrix B, so the resulting matrix will have 1 row and 2 colums.

2. We use sum of products to get the new values in the new matrix and you multiply them in the order of the new matrix. So for row 1 column 1 in the new matrix you do the sum product of row 1 in matrix A by column 1 in matrix B and so on and so forth.

In [83]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [85]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [86]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [90]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.27 ms, sys: 8.19 ms, total: 10.5 ms
Wall time: 8.15 ms


In [91]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 2.02 ms, sys: 789 μs, total: 2.81 ms
Wall time: 2.14 ms


tensor(14)

In [92]:
tensor @ tensor

tensor(14)

### One of the most common errors in matrix multiplication is shape mismatch

like I said above, but now the pytorch video guy does it again.
The inner dimensions of the matricies must match and the resulting matrix will match the outside dimensions of the matricies
i.e a (3,2) @ (2,3) gives us a (3,3) matrix

In [93]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.3865, 0.3620, 0.5545],
        [0.4904, 0.4036, 0.7429],
        [0.4232, 0.4851, 0.5450]])

In [96]:
# shapes for matrix multiplication
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])

tensor_B = torch.tensor([
    [7,10],
    [8,11],
    [9,12]
])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [97]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A transpose switches the axes or dimensions of a given tensor

In [102]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [104]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [110]:
# the matrix multiplication operation works when tensor_B is transposed 
print(f"original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"new shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <--- inner dimensions must match')
print(f'Output:\n')
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
new shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <--- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [122]:
# create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [112]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [113]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [118]:
# find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [119]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [120]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [123]:
x[0]

tensor(1)

In [124]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [128]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Commute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [153]:
# lets create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [154]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [155]:
# Change the view - pretty sure this does the same thing as the reshape cell above
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [150]:
# changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [161]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# 