In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [3]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get scalar back as python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# matrix
matrix = torch.tensor([
    [7,8],
    [9,10],
])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix[1]

tensor([ 9, 10])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
# tensor
tensor = torch.tensor([[
    [1,2,3],
    [3,6,9],
    [2,4,5]
    ]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
tensor2 = torch.tensor([[
    [1,2,3],
    [3,6,9],
    [2,4,5]
    ],[
    [1,2,3],
    [3,6,9],
    [2,4,5]
    ]])
tensor2

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
tensor2.ndim

3

In [19]:
tensor2.shape

torch.Size([2, 3, 3])

In [20]:
tensor2[1]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

random tensors?

why random tensors?

random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

start with random numbers ----> look at data ----> update random numbers ----> look at data ----> update random numbers

In [21]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6048, 0.7711, 0.7581, 0.6985],
        [0.2071, 0.0377, 0.3669, 0.8786],
        [0.7363, 0.7567, 0.1166, 0.3833]])

In [22]:
random_tensor.ndim

2

In [23]:
# create a random tensor with a similiar shape to an image tensor
random_image_size_tensor = torch.rand(224, 224, 3) # height width color_channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# create a tensor of all ones
ones = torch.ones(size=(3,4)) # using size is the same as not using it because its the default
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [28]:
# use torch.range()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros 

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors ot on the right device

In [30]:
# float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None, # what data type the tensor is (e.g. float32, int32, float16, etc)
    device=None, # which device the tensor is stored and run on aka cpu or gpu or tpu
    requires_grad=False # whether or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [34]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [35]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - tensor.dtype
2. Tensors not right shape - tensor.shape
3. Tensors ot on the right device - tensor.device

In [36]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1315, 0.1209, 0.9109, 0.6773],
        [0.4352, 0.6141, 0.7014, 0.4000],
        [0.2883, 0.7216, 0.2193, 0.2368]])

In [37]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1315, 0.1209, 0.9109, 0.6773],
        [0.4352, 0.6141, 0.7014, 0.4000],
        [0.2883, 0.7216, 0.2193, 0.2368]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [38]:
# Create a tensor and add ten to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [39]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [40]:
# Subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [41]:
# try out the pytorch built in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

imagine these matrices: 
Matrix A has 1 row and 3 columns
Matrix B has 3 rows and 2 columns

1. Matrix A must have the same columns as rows in matrix B
We can multiply A by B because 3 columns in A = 3 rows in B
But we cannot multiply B by A because 2 columns in B does not = 1 row in A

When we do multiply A by B the resulting matrix will have the same number of rows as matrix A and the same number of columns as matrix B, so the resulting matrix will have 1 row and 2 colums.

2. We use sum of products to get the new values in the new matrix and you multiply them in the order of the new matrix. So for row 1 column 1 in the new matrix you do the sum product of row 1 in matrix A by column 1 in matrix B and so on and so forth.

In [43]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [44]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [45]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [46]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 6.99 ms, sys: 1.28 ms, total: 8.27 ms
Wall time: 7.56 ms


In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 131 μs, sys: 24 μs, total: 155 μs
Wall time: 160 μs


tensor(14)

In [48]:
tensor @ tensor

tensor(14)

### One of the most common errors in matrix multiplication is shape mismatch

like I said above, but now the pytorch video guy does it again.
The inner dimensions of the matricies must match and the resulting matrix will match the outside dimensions of the matricies
i.e a (3,2) @ (2,3) gives us a (3,3) matrix

In [49]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.0361, 0.4189, 0.6924],
        [0.0041, 0.0428, 0.0925],
        [0.0309, 0.4991, 0.1873]])

In [50]:
# shapes for matrix multiplication
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])

tensor_B = torch.tensor([
    [7,10],
    [8,11],
    [9,12]
])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [51]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A transpose switches the axes or dimensions of a given tensor

In [52]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [53]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [54]:
# the matrix multiplication operation works when tensor_B is transposed 
print(f"original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"new shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <--- inner dimensions must match')
print(f'Output:\n')
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
new shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <--- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [55]:
# create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [56]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [57]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [58]:
# find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [59]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [60]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [61]:
x[0]

tensor(1)

In [62]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [63]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Commute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [64]:
# lets create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [65]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [66]:
# Change the view - pretty sure this does the same thing as the reshape cell above
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
# changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [68]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [74]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra deminesions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [77]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [78]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # height, width, color_channels

# permute the original tensor to rearrange the axis (or dimension) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # color_channels, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [82]:
# Changing a value in the original tensor will reflect in the permuted tensor because they share the same memory
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [84]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [85]:
# Let's index on our new tensor
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [87]:
# lets index on the middle bracket dim=1
x[0][0]

tensor([1, 2, 3])

In [90]:
# lets index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [92]:
# You can also use the semi colon to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [102]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [106]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [107]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy 

NumPy is a popular scientific Python numerical computing library.

and because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [108]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy to pytorch, pytorch reflects numpys default datatype of float64 unless otherwise specified
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [115]:
# change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [116]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [118]:
# Change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor   

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take random out of random)

In short how a neural network learns:

'start with random number -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [123]:
import torch

# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2913, 0.6718, 0.6985, 0.5465],
        [0.0901, 0.3399, 0.0514, 0.8480],
        [0.6990, 0.0356, 0.4006, 0.5857]])
tensor([[0.5311, 0.7036, 0.6639, 0.0772],
        [0.2309, 0.0454, 0.7242, 0.8799],
        [0.1175, 0.9068, 0.8299, 0.4445]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [130]:
# Lets make some random but reproducbile tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(4,3)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(4,3)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computations on numbers, thanks to CUDA + Nvidia hardware + PyTorch working behind the scenes to make everything hunky dory.

You can pay for colab pro which is like 9.99 per month and gives you faster GPU remote access usage.

You get like 1 free GPU with colab free version.

Or you can use your own GPU locally.

### Getting a GPU

1. Easiest - Use Google Colab for a free GPU (option to upgrade as well)

2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, theres lots of options... 

3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/


In [131]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


2. Check for GPU access with PyTorch

In [132]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False